### ISSUE TITLE
Wrong location path of NuGet.Config for linux

### ISSUE THREAD

**Issue by arthis** [NuGet/docs.microsoft.com-nuget.fr-fr#15]
In the above :
ConfigFile	The NuGet configuration file to apply. If not specified, %AppData%\NuGet\NuGet.Config (Windows) or ~/.nuget/NuGet/NuGet.Config (Mac/Linux) is used.

For linux, it is not the correct location , it should be ~/.config/NuGet/NuGet.Config

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d63170c3-1894-8ead-b557-9937dae88172
* Version Independent ID: 67968c11-0aa0-f835-357d-8690911eb011
* Content: [Commande de restauration NuGet CLI](https://docs.microsoft.com/fr-fr/nuget/tools/cli-ref-restore#feedback)
* Content Source: [docs/tools/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget.fr-fr/blob/live/docs/tools/cli-ref-restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
Hello, @arthis 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/NuGet/docs.microsoft.com-nuget/issues/1451

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
